AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Fargate Setup for .NET 8 POC

Resources:

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: pocnet8aws-cluster

  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP inbound
      VpcId: vpc-xxxxx
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Fn::Ref: ECSCluster
      LaunchType: FARGATE
      DesiredCount: 1
      TaskDefinition: arn:aws:ecs:REGION:ACCOUNT_ID:task-definition/pocnet8aws-task
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-xxxxx
            - subnet-yyyyy
          SecurityGroups:
            - Fn::Ref: ServiceSecurityGroup
